export const avatarPaths = [
  'images/avatars/man_01.svg',
  'images/avatars/man_02.svg',
  'images/avatars/man_03.svg',
  'images/avatars/man_04.svg',
  'images/avatars/man_05.svg',
  'images/avatars/man_06.svg',
  'images/avatars/man_07.svg',
  'images/avatars/man_08.svg',
  'images/avatars/man_09.svg',
  'images/avatars/man_10.svg',
  'images/avatars/man_11.svg',
  'images/avatars/man_12.svg',
  'images/avatars/man_13.svg',
  'images/avatars/man_14.svg',
  'images/avatars/man_15.svg',
  'images/avatars/woman_01.svg',
  'images/avatars/woman_02.svg',
  'images/avatars/woman_03.svg',
  'images/avatars/woman_04.svg',
  'images/avatars/woman_05.svg',
  'images/avatars/woman_06.svg',
  'images/avatars/woman_07.svg',
  'images/avatars/woman_08.svg',
  'images/avatars/woman_09.svg',
  'images/avatars/woman_10.svg',
  'images/avatars/woman_11.svg',
  'images/avatars/woman_12.svg',
  'images/avatars/woman_13.svg',
  'images/avatars/woman_14.svg',
  'images/avatars/woman_15.svg',
];

export const avatarInfo = [
  { name: 'Joe', path: 'images/avatars/man_01.svg' },
  { name: 'Jerry', path: 'images/avatars/man_02.svg' },
];
